apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: api-deployment
  template:
    metadata:
      name: api-deployment
      labels:
        app: api-deployment
    spec:
      containers:
        - name: api-deployment
          image: fabricioveronez/pedelogo-catalogo:1.0.0
          ports:
            - containerPort: 80
              protocol: TCP
              name: http
            - containerPort: 443
              protocol: TCP
              name: https
          imagePullPolicy: Always # Always | Never | IfNotPresent
          resources: {}
          env:
            - name: Mongo__Host
              value: "mongo-service"
            - name: Mongo__User
              value: "mongouser"
            - name: Mongo__Password
              value: "mongopwd"
            - name: Mongo__Port
              value: "27017"
            - name: Mongo__DataBase
              value: "admin"
